### ISSUE TITLE
<Bug> Leanback icon missing

### ISSUE THREAD

**Issue by peat80** [wabosh/KennyTV#1]
This app does not show an banner icon on android tv.
So it does not show in default tv launcher.

You have to find it under all apps and launch from there  or use a custom launcher.

Once startet it works fine on tv using the remote control.

Nice app so far. 😍👌

**Comment by wabosh** [comment]
I just released a new version with the correct entries in AndroidManifest.xml.

**Comment by peat80** [comment]
What a fast fix. 😎👍

I can confirm that the fix works. 👌
