### ISSUE TITLE
Web Scraping Error on app launch

### ISSUE THREAD

**Issue by woogi-kang** [wabosh/KennyTV#4]
Hi there, great project.

I tried to run the project but while on app launch, web_scraping

episodes_provider > fetchSeasons() gets Null check operator used on a null value error while parsing Season Model.

I think the dom data from the southpark has been changed. 

Can you fix this error?

**Comment by wabosh** [comment]
I think that might be due geo-related reasons. Currently it's only working in germany but i've started reworking it to use a better method of gettting seasons and episodes.

**Comment by woogi-kang** [comment]
Thanks for the reply. I look forward to it!
